/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as LearnerRouteImport } from './routes/learner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as SessionLearnerIdRouteImport } from './routes/session.$learnerId'
import { Route as ParentLearnersRouteImport } from './routes/parent.learners'
import { Route as FlashcardsLearnerIdRouteImport } from './routes/flashcards.$learnerId'
import { Route as ParentSessionsLearnerIdRouteImport } from './routes/parent.sessions.$learnerId'
import { Route as ParentQuickSetupLearnerIdRouteImport } from './routes/parent.quick-setup.$learnerId'
import { Route as ParentPhonicsLearnerIdRouteImport } from './routes/parent.phonics.$learnerId'
import { Route as ParentInterferenceLearnerIdRouteImport } from './routes/parent.interference.$learnerId'
import { Route as ParentBenchmarkLearnerIdRouteImport } from './routes/parent.benchmark.$learnerId'
import { Route as ParentAssessmentLearnerIdRouteImport } from './routes/parent.assessment.$learnerId'

const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerRoute = LearnerRouteImport.update({
  id: '/learner',
  path: '/learner',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const SessionLearnerIdRoute = SessionLearnerIdRouteImport.update({
  id: '/session/$learnerId',
  path: '/session/$learnerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentLearnersRoute = ParentLearnersRouteImport.update({
  id: '/learners',
  path: '/learners',
  getParentRoute: () => ParentRoute,
} as any)
const FlashcardsLearnerIdRoute = FlashcardsLearnerIdRouteImport.update({
  id: '/flashcards/$learnerId',
  path: '/flashcards/$learnerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentSessionsLearnerIdRoute = ParentSessionsLearnerIdRouteImport.update({
  id: '/sessions/$learnerId',
  path: '/sessions/$learnerId',
  getParentRoute: () => ParentRoute,
} as any)
const ParentQuickSetupLearnerIdRoute =
  ParentQuickSetupLearnerIdRouteImport.update({
    id: '/quick-setup/$learnerId',
    path: '/quick-setup/$learnerId',
    getParentRoute: () => ParentRoute,
  } as any)
const ParentPhonicsLearnerIdRoute = ParentPhonicsLearnerIdRouteImport.update({
  id: '/phonics/$learnerId',
  path: '/phonics/$learnerId',
  getParentRoute: () => ParentRoute,
} as any)
const ParentInterferenceLearnerIdRoute =
  ParentInterferenceLearnerIdRouteImport.update({
    id: '/interference/$learnerId',
    path: '/interference/$learnerId',
    getParentRoute: () => ParentRoute,
  } as any)
const ParentBenchmarkLearnerIdRoute =
  ParentBenchmarkLearnerIdRouteImport.update({
    id: '/benchmark/$learnerId',
    path: '/benchmark/$learnerId',
    getParentRoute: () => ParentRoute,
  } as any)
const ParentAssessmentLearnerIdRoute =
  ParentAssessmentLearnerIdRouteImport.update({
    id: '/assessment/$learnerId',
    path: '/assessment/$learnerId',
    getParentRoute: () => ParentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learner': typeof LearnerRoute
  '/parent': typeof ParentRouteWithChildren
  '/flashcards/$learnerId': typeof FlashcardsLearnerIdRoute
  '/parent/learners': typeof ParentLearnersRoute
  '/session/$learnerId': typeof SessionLearnerIdRoute
  '/parent/': typeof ParentIndexRoute
  '/parent/assessment/$learnerId': typeof ParentAssessmentLearnerIdRoute
  '/parent/benchmark/$learnerId': typeof ParentBenchmarkLearnerIdRoute
  '/parent/interference/$learnerId': typeof ParentInterferenceLearnerIdRoute
  '/parent/phonics/$learnerId': typeof ParentPhonicsLearnerIdRoute
  '/parent/quick-setup/$learnerId': typeof ParentQuickSetupLearnerIdRoute
  '/parent/sessions/$learnerId': typeof ParentSessionsLearnerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learner': typeof LearnerRoute
  '/flashcards/$learnerId': typeof FlashcardsLearnerIdRoute
  '/parent/learners': typeof ParentLearnersRoute
  '/session/$learnerId': typeof SessionLearnerIdRoute
  '/parent': typeof ParentIndexRoute
  '/parent/assessment/$learnerId': typeof ParentAssessmentLearnerIdRoute
  '/parent/benchmark/$learnerId': typeof ParentBenchmarkLearnerIdRoute
  '/parent/interference/$learnerId': typeof ParentInterferenceLearnerIdRoute
  '/parent/phonics/$learnerId': typeof ParentPhonicsLearnerIdRoute
  '/parent/quick-setup/$learnerId': typeof ParentQuickSetupLearnerIdRoute
  '/parent/sessions/$learnerId': typeof ParentSessionsLearnerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learner': typeof LearnerRoute
  '/parent': typeof ParentRouteWithChildren
  '/flashcards/$learnerId': typeof FlashcardsLearnerIdRoute
  '/parent/learners': typeof ParentLearnersRoute
  '/session/$learnerId': typeof SessionLearnerIdRoute
  '/parent/': typeof ParentIndexRoute
  '/parent/assessment/$learnerId': typeof ParentAssessmentLearnerIdRoute
  '/parent/benchmark/$learnerId': typeof ParentBenchmarkLearnerIdRoute
  '/parent/interference/$learnerId': typeof ParentInterferenceLearnerIdRoute
  '/parent/phonics/$learnerId': typeof ParentPhonicsLearnerIdRoute
  '/parent/quick-setup/$learnerId': typeof ParentQuickSetupLearnerIdRoute
  '/parent/sessions/$learnerId': typeof ParentSessionsLearnerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learner'
    | '/parent'
    | '/flashcards/$learnerId'
    | '/parent/learners'
    | '/session/$learnerId'
    | '/parent/'
    | '/parent/assessment/$learnerId'
    | '/parent/benchmark/$learnerId'
    | '/parent/interference/$learnerId'
    | '/parent/phonics/$learnerId'
    | '/parent/quick-setup/$learnerId'
    | '/parent/sessions/$learnerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/learner'
    | '/flashcards/$learnerId'
    | '/parent/learners'
    | '/session/$learnerId'
    | '/parent'
    | '/parent/assessment/$learnerId'
    | '/parent/benchmark/$learnerId'
    | '/parent/interference/$learnerId'
    | '/parent/phonics/$learnerId'
    | '/parent/quick-setup/$learnerId'
    | '/parent/sessions/$learnerId'
  id:
    | '__root__'
    | '/'
    | '/learner'
    | '/parent'
    | '/flashcards/$learnerId'
    | '/parent/learners'
    | '/session/$learnerId'
    | '/parent/'
    | '/parent/assessment/$learnerId'
    | '/parent/benchmark/$learnerId'
    | '/parent/interference/$learnerId'
    | '/parent/phonics/$learnerId'
    | '/parent/quick-setup/$learnerId'
    | '/parent/sessions/$learnerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnerRoute: typeof LearnerRoute
  ParentRoute: typeof ParentRouteWithChildren
  FlashcardsLearnerIdRoute: typeof FlashcardsLearnerIdRoute
  SessionLearnerIdRoute: typeof SessionLearnerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner': {
      id: '/learner'
      path: '/learner'
      fullPath: '/learner'
      preLoaderRoute: typeof LearnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/session/$learnerId': {
      id: '/session/$learnerId'
      path: '/session/$learnerId'
      fullPath: '/session/$learnerId'
      preLoaderRoute: typeof SessionLearnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/learners': {
      id: '/parent/learners'
      path: '/learners'
      fullPath: '/parent/learners'
      preLoaderRoute: typeof ParentLearnersRouteImport
      parentRoute: typeof ParentRoute
    }
    '/flashcards/$learnerId': {
      id: '/flashcards/$learnerId'
      path: '/flashcards/$learnerId'
      fullPath: '/flashcards/$learnerId'
      preLoaderRoute: typeof FlashcardsLearnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/sessions/$learnerId': {
      id: '/parent/sessions/$learnerId'
      path: '/sessions/$learnerId'
      fullPath: '/parent/sessions/$learnerId'
      preLoaderRoute: typeof ParentSessionsLearnerIdRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/quick-setup/$learnerId': {
      id: '/parent/quick-setup/$learnerId'
      path: '/quick-setup/$learnerId'
      fullPath: '/parent/quick-setup/$learnerId'
      preLoaderRoute: typeof ParentQuickSetupLearnerIdRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/phonics/$learnerId': {
      id: '/parent/phonics/$learnerId'
      path: '/phonics/$learnerId'
      fullPath: '/parent/phonics/$learnerId'
      preLoaderRoute: typeof ParentPhonicsLearnerIdRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/interference/$learnerId': {
      id: '/parent/interference/$learnerId'
      path: '/interference/$learnerId'
      fullPath: '/parent/interference/$learnerId'
      preLoaderRoute: typeof ParentInterferenceLearnerIdRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/benchmark/$learnerId': {
      id: '/parent/benchmark/$learnerId'
      path: '/benchmark/$learnerId'
      fullPath: '/parent/benchmark/$learnerId'
      preLoaderRoute: typeof ParentBenchmarkLearnerIdRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/assessment/$learnerId': {
      id: '/parent/assessment/$learnerId'
      path: '/assessment/$learnerId'
      fullPath: '/parent/assessment/$learnerId'
      preLoaderRoute: typeof ParentAssessmentLearnerIdRouteImport
      parentRoute: typeof ParentRoute
    }
  }
}

interface ParentRouteChildren {
  ParentLearnersRoute: typeof ParentLearnersRoute
  ParentIndexRoute: typeof ParentIndexRoute
  ParentAssessmentLearnerIdRoute: typeof ParentAssessmentLearnerIdRoute
  ParentBenchmarkLearnerIdRoute: typeof ParentBenchmarkLearnerIdRoute
  ParentInterferenceLearnerIdRoute: typeof ParentInterferenceLearnerIdRoute
  ParentPhonicsLearnerIdRoute: typeof ParentPhonicsLearnerIdRoute
  ParentQuickSetupLearnerIdRoute: typeof ParentQuickSetupLearnerIdRoute
  ParentSessionsLearnerIdRoute: typeof ParentSessionsLearnerIdRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentLearnersRoute: ParentLearnersRoute,
  ParentIndexRoute: ParentIndexRoute,
  ParentAssessmentLearnerIdRoute: ParentAssessmentLearnerIdRoute,
  ParentBenchmarkLearnerIdRoute: ParentBenchmarkLearnerIdRoute,
  ParentInterferenceLearnerIdRoute: ParentInterferenceLearnerIdRoute,
  ParentPhonicsLearnerIdRoute: ParentPhonicsLearnerIdRoute,
  ParentQuickSetupLearnerIdRoute: ParentQuickSetupLearnerIdRoute,
  ParentSessionsLearnerIdRoute: ParentSessionsLearnerIdRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnerRoute: LearnerRoute,
  ParentRoute: ParentRouteWithChildren,
  FlashcardsLearnerIdRoute: FlashcardsLearnerIdRoute,
  SessionLearnerIdRoute: SessionLearnerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
